services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev  # 개발 프로파일 사용

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
